### ISSUE TITLE
调用 ExportByTemplate<T>(path, output, tplPath)的时候出错

### ISSUE THREAD

**Issue by xujinmin19910101** [xin-lai/Magicodes.ExporterAndImporter#545]
![image](https://github.com/dotnetcore/Magicodes.IE/assets/137074839/de568193-b5d3-47b9-9e75-20441855abf9)
你好，在调用ExportByTemplate的时候报图片上面的异常，请问如何解决

**Comment by xujinmin19910101** [comment]
![image](https://github.com/dotnetcore/Magicodes.IE/assets/137074839/38976a60-9a07-4b18-a803-bd73f5ee00cf)
这个是nuget的版本

**Comment by hueifeng** [comment]
可以检查下依赖的项目类库，是否存在引用了高版本的“SixLabors.ImageSharp”包
![image](https://github.com/dotnetcore/Magicodes.IE/assets/34702552/e1f32e00-6be5-4211-be65-617935a3deb7)

**Comment by xujinmin19910101** [comment]
我发现2.1.3版本和我用的3.1.0版本的 SixLabors.ImageSharp 少了两个东西，请问是否要更新？
![lQLPKILDFEtnt79tzQEcsN9fx3F-dyGbBYZ1dDu1WwA_284_109](https://github.com/dotnetcore/Magicodes.IE/assets/137074839/15b0c966-113d-43cc-a2fc-979bd11ac81e)
